[cross_compil] Updated IPOPT_LIB_DYNAMIC because of compilation error
[660/688] Linking CXX shared library libssc_ipopt_interface_shared.dll
FAILED: libssc_ipopt_interface_shared.dll libssc_ipopt_interface_shared.dll.a
: && /usr/src/mxe/usr/bin/x86_64-w64-mingw32.static-g++  -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -ffast-math -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -O3 -DEIGEN_NO_DEBUG -O3 -DNDEBUG   -shared -o libssc_ipopt_interface_shared.dll -Wl,--out-implib,libssc_ipopt_interface_shared.dll.a -Wl,--major-image-version,0,--minor-image-version,0 ipopt_interface/CMakeFiles/ipopt_interface_object.dir/InternalIpopt.cpp.obj ipopt_interface/CMakeFiles/ipopt_interface_object.dir/IpoptParameters.cpp.obj ipopt_interface/CMakeFiles/ipopt_interface_object.dir/IpoptSolver.cpp.obj  libssc_optimizer_shared.dll.a /opt/CoinIpopt/lib/libipopt.a /opt/CoinIpopt/lib/libcoinmumps.a /opt/CoinIpopt/lib/libcoinlapack.a /opt/CoinIpopt/lib/libcoinblas.a -lgfortran -lgcc_s -lm libssc_functors_for_optimizer_shared.dll.a libssc_interpolation_shared.dll.a libssc_matrix_and_vector_classes_shared.dll.a libssc_exception_handling_shared.dll.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static-ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
[661/688] Building CXX object optimizer/unit_tests/CMakeFiles/optimizer_tests.dir/src/OptimizationProblemTest.cpp.obj
ninja: build stopped: subcommand failed.