Fixed a compilation warning for function tmpnam
Output value of this function was not used...

[ 91%] Building CXX object csv_file_reader/unit_tests/CMakeFiles/csv_file_reader_tests.dir/src/CSVFileReaderTest.cpp.o
/home/jacquenot/Work/git/SimulateurIrtJv/code/csv_file_reader/unit_tests/src/CSVFileReaderTest.cpp: In member function ‘virtual void CSVFileReaderTest_example_Test::TestBody()’:
/home/jacquenot/Work/git/SimulateurIrtJv/code/csv_file_reader/unit_tests/src/CSVFileReaderTest.cpp:34:19: error: ignoring return value of ‘char* tmpnam(char*)’, declared with attribute warn_unused_result [-Werror=unused-result]
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [csv_file_reader/unit_tests/CMakeFiles/csv_file_reader_tests.dir/src/CSVFileReaderTest.cpp.o] Erreur 1
make[1]: *** [csv_file_reader/unit_tests/CMakeFiles/csv_file_reader_tests.dir/all] Erreur 2
make: *** [all] Erreur 2
Running tests...

git-svn-id: http://130.66.124.6/svn/maroff/Product/Cpp/Tools/csv_file_reader@1726 300066c3-8af3-463d-8cc0-c0233cc64ac1