:bug: Fixed a compilation bug that appeared with gcc 10.2
[2/218] Building CXX object data_source/unit_tests/CMakeFiles/data_source_tests.dir/src/SignalContainerTest.cpp.obj
FAILED: data_source/unit_tests/CMakeFiles/data_source_tests.dir/src/SignalContainerTest.cpp.obj
/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static.posix-g++ -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I../.. -isystem ../data_source/unit_tests/inc -isystem ../google-test/googletest/include -isystem ../google-test/googletest/include/gtest -isystem ../google-test/googlemock/include -isystem ../google-test/googlemock/include/gmock -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -O3 -DEIGEN_NO_DEBUG -O3 -DNDEBUG -MD -MT data_source/unit_tests/CMakeFiles/data_source_tests.dir/src/SignalContainerTest.cpp.obj -MF data_source/unit_tests/CMakeFiles/data_source_tests.dir/src/SignalContainerTest.cpp.obj.d -o data_source/unit_tests/CMakeFiles/data_source_tests.dir/src/SignalContainerTest.cpp.obj -c ../data_source/unit_tests/src/SignalContainerTest.cpp
In file included from ../data_source/unit_tests/src/SignalContainerTest.cpp:9:
../../ssc/data_source/SignalContainer.hpp: In member function 'std::vector<ssc::data_source::TypedSignalName> ssc::data_source::SignalContainer::get_closest_match(const ssc::data_source::TypedSignalName&) const':
../../ssc/data_source/SignalContainer.hpp:57:55: error: implicitly-declared 'ssc::data_source::TypedSignalName::TypedSignalName(const ssc::data_source::TypedSignalName&)' is deprecated [-Werror=deprecated-copy]
   57 |                         const TypedSignalName s = it->first;
      |                                                       ^~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make: *** [Makefile:81: windows_build] Error 1
sirehna@debian:~/ssc$ s