[master] Adding missing SSC dependency to geometry library. Problem detected on WinXP 32 bits
Scanning dependencies of target geometry_shared
Linking CXX shared library libssc_geometry-Windows-32bits-mgw45-release-1-0-0_shared.dll
Creating library file: libssc_geometry-Windows-32bits-mgw45-release-1-0-0_shared.dll.aCMakeFiles/geometry_shared.dir/objects.a(Track.cpp.obj):Track.cpp:(.text+0x35a): undefined reference to `ssc::interpolation::IndexFinder::compute(double)'
CMakeFiles/geometry_shared.dir/objects.a(Track.cpp.obj):Track.cpp:(.text$_ZN3ssc8geometry5Track9TrackImplC1ERKSt6vectorINS0_17LatitudeLongitudeESaIS4_EEPNS0_8LegChainE[ssc::geometry::Track::TrackImpl::TrackImpl(std::vector<ssc::geometry::LatitudeLongitude, std::allocator<ssc::geometry::LatitudeLongitude> > const&, ssc::geometry::LegChain*)]+0x157): undefined reference to `ssc::interpolation::IndexFinder::IndexFinder(std::vector<double, std::allocator<double> > const&, bool)'
CMakeFiles/geometry_shared.dir/objects.a(Track.cpp.obj):Track.cpp:(.text$_ZN3ssc8geometry5Track9TrackImplC1ERKSt6vectorINS0_17LatitudeLongitudeESaIS4_EEPNS0_8LegChainE[ssc::geometry::Track::TrackImpl::TrackImpl(std::vector<ssc::geometry::LatitudeLongitude, std::allocator<ssc::geometry::LatitudeLongitude> > const&, ssc::geometry::LegChain*)]+0x8bb): undefined reference to `ssc::interpolation::IndexFinder::IndexFinder(std::vector<double, std::allocator<double> > const&, bool
)'
collect2: ld returned 1 exit status
make[3]: *** [libssc_geometry-Windows-32bits-mgw45-release-1-0-0_shared.dll] Error 1