[fix_compilation_gcc610] Fixed ssc/decode_unit/DecodeUnit.cpp
Scanning dependencies of target decode_unit_object
[  5%] Building CXX object
decode_unit/CMakeFiles/decode_unit_object.dir/DecodeUnit.cpp.obj
d:/Jenkins/jobs/ScientificComputing_Win7_GCC610/workspace/ssc/decode_unit/DecodeUnit.cpp:
In member function 'ssc::decode_unit::UnitDecoder::Token*
ssc::decode_unit::UnitDecoder::scan()':
d:/Jenkins/jobs/ScientificComputing_Win7_GCC610/workspace/ssc/decode_unit/DecodeUnit.cpp:176:65:
error: conversion to 'char' from 'int' may alter its value
[-Werror=conversion]
    throw std::string("unexpected character : ") +
    std::string(1,m_next_char);

compilation terminated due to -Wfatal-errors.
cc1plus.exe: all warnings being treated as errors
make[2]: ***
[decode_unit/CMakeFiles/decode_unit_object.dir/DecodeUnit.cpp.obj] Error 1
make[1]: *** [decode_unit/CMakeFiles/decode_unit_object.dir/all] Error 2
make: *** [all] Error 2