[gcc8] Fixed a typo warning detected with gcc 8
../functors_for_optimizer/unit_tests/src/FunctorAlgebraTest.cpp:580:12: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
         if (x->get_lambda()() >= 0) ASSERT_EQ(1, f->get_lambda()());
            ^
compilation terminated due to -Wfatal-errors.